// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import <Foundation/Foundation.h>

@interface DBParcelableSet : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithSet:(nonnull NSSet<NSString *> *)set NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)parcelableSetWithSet:(nonnull NSSet<NSString *> *)set;

@property (nonatomic, readonly, nonnull) NSSet<NSString *> * set;

@end
