// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import <Foundation/Foundation.h>

@interface DBParcelableOptionalList : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithOptionalSet:(nullable NSArray<NSString *> *)optionalSet NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)parcelableOptionalListWithOptionalSet:(nullable NSArray<NSString *> *)optionalSet;

@property (nonatomic, readonly, nullable) NSArray<NSString *> * optionalSet;

@end
