// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#import <Foundation/Foundation.h>

@interface DBParcelableOptionalSet : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithOptionalSet:(nullable NSSet<NSString *> *)optionalSet NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)parcelableOptionalSetWithOptionalSet:(nullable NSSet<NSString *> *)optionalSet;

@property (nonatomic, readonly, nullable) NSSet<NSString *> * optionalSet;

@end
